// Site
export const SITE_LOADING = 'SITE_LOADING';
export const SITE_LOADED = 'SITE_LOADED';
export const SET_SIDEBAR_TOGGLER = 'SET_SIDEBAR_TOGGLER';

export const HIDE_SITE_MESSAGE = 'HIDE_SITE_MESSAGE';

// Layout
export const SET_MOBILE_MENU = 'SET_MOBILE_MENU';

// Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

// Profile
export const ENABLE_FIELDS = 'ENABLE_FIELDS';

// Auth
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const ACTIVATING_USER = 'ACTIVATING_USER';
export const USER_ACTIVATED = 'USER_ACTIVATED';
export const ACTIVATION_FAILED = 'ACTIVATION_FAILED';

export const SOCIAL_AUTH_SUCCESS = 'SOCIAL_AUTH_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const USER_UPDATED = 'USER_UPDATED';
export const UPDATE_ERROR = 'UPDATE_ERROR';
export const AUTH_ERROR = 'AUTH_ERROR';

export const REQUEST_LOADING = 'REQUEST_LOADING';
export const PASSWORD_UPDATE = 'PASSWORD_UPDATE';
export const REQUEST_PROCESSED = 'REQUEST_PROCESSED';

export const ADDRESS_ADDED = 'ADDRESS_ADDED';
export const ADDRESS_DELETED = 'ADDRESS_DELETED';
export const ADDRESS_UPDATED = 'ADDRESS_UPDATED';

// Auth - Verification
export const VERIFYING_PASSWORD_RESET = 'VERIFYING_PASSWORD_RESET';
export const VERIFIED_PASSWORD_RESET = 'VERIFIED_PASSWORD_RESET';
export const PASSWORD_RESET_VERIFICATION_ERROR = 'PASSWORD_RESET_VERIFICATION_ERROR';
export const PASSWORD_RESET_DONE = 'PASSWORD_RESET_DONE';

// Articles
export const ARTICLES_LOADING = 'ARTICLES_LOADING';
export const ARTICLE_LOADING = 'ARTICLE_LOADING';
export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLE = 'GET_ARTICLE';
export const ARTICLE_ERROR = 'ARTICLE_ERROR';
export const ARTICLE_PAGE = 'ARTICLE_PAGE';

// Events
export const EVENT_LOADING = 'EVENT_LOADING';
export const GET_EVENT = 'GET_EVENT';
export const EVENT_ERROR = 'EVENT_ERROR';

// Services
export const SERVICE_LOADING = 'SERVICE_LOADING';
export const GET_SERVICES = 'GET_SERVICES';
export const SERVICE_ERROR = 'SERVICE_ERROR';

// Contact
export const CONTACTING = 'CONTACTING';
export const CONTACTED = 'CONTACTED';

// Shop
export const GET_FILTER_DETAILS = 'GET_FILTER_DETAILS';

export const SELLER_LOADING = 'SELLER_LOADING';
export const GET_SELLER = 'GET_SELLER';
export const SELLER_ERROR = 'SELLER_ERROR';

export const SELLER_PRODUCTS_LOADING = 'SELLER_PRODUCTS_LOADING';
export const GET_SELLER_PRODUCTS = 'GET_SELLER_PRODUCTS';
export const SELLER_PRODUCTS_ERROR = 'SELLER_PRODUCTS_ERROR';
export const MORE_SELLER_PRODUCTS_LOADING = 'MORE_SELLER_PRODUCTS_LOADING';
export const GET_MORE_SELLER_PRODUCTS = 'GET_MORE_SELLER_PRODUCTS';
export const SELLER_PRODUCTS_PAGE = 'SELLER_PRODUCTS_PAGE';

// Shop - Highlights
export const GET_HIGHLIGHTS = 'GET_HIGHLIGHTS';

// Shop - Products
export const ALL_PRODUCTS_LOADING = 'ALL_PRODUCTS_LOADING';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const ALL_PRODUCTS_ERROR = 'ALL_PRODUCTS_ERROR';

export const PRODUCTS_PAGE = 'PRODUCTS_PAGE';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const MORE_PRODUCTS_LOADING = 'MORE_PRODUCTS_LOADING';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_MORE_PRODUCTS = 'GET_MORE_PRODUCTS';
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';

export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const GET_PRODUCT = 'GET_PRODUCT';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';

export const FILTER_CATEGORY = 'FILTER_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY';

export const FILTER_SELLER = 'FILTER_SELLER';
export const REMOVE_SELLER = 'REMOVE_SELLER';
export const CLEAR_SELLER = 'CLEAR_SELLER';

export const FILTER_KEYWORDS = 'FILTER_KEYWORDS';
export const CLEAR_KEYWORDS = 'CLEAR_KEYWORDS';

// Shopping
// Orders
export const CURRENT_ORDER_LOADING = 'CURRENT_ORDER_LOADING';
export const GET_CURRENT_ORDER = 'GET_CURRENT_ORDER';
export const CURRENT_ORDER_ERROR = 'CURRENT_ORDER_ERROR';

export const ORDERS_LOADING = 'ORDERS_LOADING';
export const MORE_ORDERS_LOADING = 'MORE_ORDERS_LOADING';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_MORE_ORDERS = 'GET_MORE_ORDERS';
export const ORDERS_ERROR = 'ORDERS_ERROR';
export const SET_ORDERS_PAGE = 'SET_ORDERS_PAGE';
export const FILTER_CURRENT_ONLY = 'FILTER_CURRENT_ONLY';

export const CHECKOUT_LOADING = 'CHECKOUT_LOADING';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILED = 'CHECKOUT_FAILED';

export const FAVORITES_LOADING = 'FAVORITES_LOADING';

export const GET_FAVORITES = 'GET_FAVORITES';

export const QUANTITY_LOADING = 'QUANTITY_LOADING';
export const QUANTITY_CHANGED = 'QUANTITY_CHANGED';
export const QUANTITY_CHANGE_ERROR = 'QUANTITY_CHANGE_ERROR';

export const DELETE_LOADING = 'DELETE_LOADING';
export const DELETE_ORDER_ITEM = 'DELETE_ORDER_ITEM';
export const DELETE_ERROR = 'DELETE_ERROR';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';

export const COMPLETE_ORDER_LOADING = 'COMPLETE_ORDER_LOADING';
export const COMPLETE_ORDER_SUCCESS = 'COMPLETE_ORDER_SUCCESS';
export const COMPLETE_ORDER_FAILED = 'COMPLETE_ORDER_FAILED';

export const ORDER_ITEM_LOADING = 'ORDER_ITEM_LOADING';
export const GET_ORDER_ITEM = 'GET_ORDER_ITEM';
export const ORDER_ITEM_ERROR = 'ORDER_ITEM_ERROR';
export const REVIEW_PRODUCT = 'REVIEW_PRODUCT';
export const REVIEW_PRODUCT_ORDER = 'REVIEW_PRODUCT_ORDER';


export const ORDER_LOADING = 'ORDER_LOADING';
export const GET_ORDER = 'GET_ORDER';
export const REVIEW_ORDER = 'REVIEW_ORDER';
export const ORDER_ERROR = 'ORDER_ERROR';

// Manager
export const DASHBOARD_LOADING = 'DASHBOARD_LOADING';
export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA';
export const DASHBOARD_DATA_ERROR = 'DASHBOARD_DATA_ERROR';

export const GET_MANAGER_ORDER_ITEMS = 'GET_MANAGER_ORDER_ITEMS';
export const MANAGER_ORDER_ITEMS_ERROR = 'MANAGER_ORDER_ITEMS_ERROR';

export const GET_MANAGER_ORDERS = 'GET_MANAGER_ORDERS';
export const MANAGER_ORDERS_ERROR = 'MANAGER_ORDERS_ERROR';

export const MANAGER_ORDER_LOADING = 'MANAGER_ORDER_LOADING';
export const GET_MANAGER_ORDER = 'GET_MANAGER_ORDER';
export const MANAGER_ORDER_ERROR = 'MANAGER_ORDER_ERROR';

export const PROCESS_ORDER = 'PROCESS_ORDER';

export const DELIVER_ORDER_ITEM = 'DELIVER_ORDER_ITEM';
export const DELIVER_ORDER = 'DELIVER_ORDER';

export const PREPARE_ORDER_ITEM = 'PREPARE_ORDER_ITEM';
export const PREPARE_ORDER = 'PREPARE_ORDER';

export const SYNC_ORDER = 'SYNC_ORDER';